# Chapter 2: Data Extraction

In this chapter, we consider the practicalities of parsing team data-files containing results of past
[Australian Football League](1_introduction.ipynb#Background "Chapter 1: Background") 
(AFL) matches, in order to create a single data file representing a combined, temporal graph of all matches across all (selected) seasons.

The major sections of this chapter are as follows:

* [Parse the Matches](#Parse-the-Matches "Section: Parse the Matches")
* [Construct the Graph](#Construct-the-Graph "Section: Construct the Graph")
* [Perform Sanity Checking](#Perform-Sanity-Checking "Section: Perform Sanity Checking")
* [Training and Testing Data](#Training-and-Testing-Data "Section: Training and Testing Data")

---

## Parse the Matches

The data-files were formed by saving the entire match data (over all seasons) separately for each team, found as web pages on [AFL Tables](https://afltables.com/afl/afl_index.html "afltables.com"). Note that it doesn't matter what file ending is used, e.g. `.htm` or `.html`. 

However, the filenames **must** match the team names, since the data-file for each team records only the opposing team names. In the case of teams that have changed name over time (excluding those that have merged with other teams), we name the data-file after the modern team name, and manually remap this to the older team name(s) when appropriate.

Also note that these data-files contain matches for both the AFL and its predecessor, the VFL (Victorian Football League). We extract only the AFL data from 1990 onwards.

In [1]:
import sys
import os

sys.path.append(os.path.join("..", "python"))

In [2]:
import pandas as pd

import match_parser

In [3]:
team_files = match_parser.get_team_files(os.path.join("..", "matches"))

In [4]:
matches = {}
for team_file in team_files:
    print("Parsing:", team_file)
    team_name = match_parser.parse_team_name(team_file)
    team_matches = match_parser.parse_team_seasons(team_file, min_season=1990)
    matches[team_name] = team_matches
print(f"Parsed {len(matches)} teams.")

Parsing: ..\matches\Adelaide.htm
Parsing: ..\matches\Brisbane Bears.htm
Parsing: ..\matches\Brisbane Lions.htm
Parsing: ..\matches\Carlton.htm
Parsing: ..\matches\Collingwood.htm
Parsing: ..\matches\Essendon.htm
Parsing: ..\matches\Fitzroy.htm
Parsing: ..\matches\Fremantle.htm
Parsing: ..\matches\Geelong.htm
Parsing: ..\matches\Gold Coast.htm
Parsing: ..\matches\Greater Western Sydney.htm
Parsing: ..\matches\Hawthorn.htm
Parsing: ..\matches\Melbourne.htm
Parsing: ..\matches\North Melbourne.htm
Parsing: ..\matches\Port Adelaide.htm
Parsing: ..\matches\Richmond.htm
Parsing: ..\matches\St Kilda.htm
Parsing: ..\matches\Sydney.htm
Parsing: ..\matches\West Coast.htm
Parsing: ..\matches\Western Bulldogs.htm
Parsed 20 teams.

---

## Construct the Graph

For convenience, we may consider each team as a vertex in a graph, and each match as an
edge between vertices. In order that each match is represented exactly once, we arbitrarily designate one of the teams to be the *'for'* team, and the opposing team to be
the *'against'* team. Hence, each edge is directed from the 'for' team to the 'against' team, and the match outcome (i.e. win, draw or loss) is specified with respect to the
'for' team.

### Team naming

We have to deal with the issue of teams changing names over time, as listed in the
[introduction](1_introduction.ipynb#AFL-Teams "Introduction: AFL Teams").
The major problem here is due to the way the data are recorded. In particular, we nominally have a data-file of matches for each team, but that team's name does not explicitly appear in the data-file, only the names of the opposing teams. 
More exactly, the title within each data-file specifies one or more alternative names for the team. If multiple names are
specified, then it is not apparent which name was used for any given match.
For example, matches involving the Kangaroos implicitly appear in the North Melbourne data-file, and matches for
Footscray implicitly appear in the Western Bulldogs data-file.
Thus, we have to guess the correct team names from the available filenames and the season.

In [5]:
all_teams = set(matches.keys())
for team_matches in matches.values():
    for df_matches in team_matches.values():
        all_teams |= set(df_matches.Opponent)
all_teams = sorted(list(all_teams))
print(f"Found {len(all_teams)} teams")
print(all_teams)

Found 22 teams
['Adelaide', 'Brisbane Bears', 'Brisbane Lions', 'Carlton', 'Collingwood', 'Essendon', 'Fitzroy', 'Footscray', 'Fremantle', 'Geelong', 'Gold Coast', 'Greater Western Sydney', 'Hawthorn', 'Kangaroos', 'Melbourne', 'North Melbourne', 'Port Adelaide', 'Richmond', 'St Kilda', 'Sydney', 'West Coast', 'Western Bulldogs']

As expected, observe that North Melbourne and Kangaroos both appear in the raw data, despite being the same team.
Similarly, Footscray is the older name of the Western Bulldogs. Thus, we could map the older names to the newer names, or the newer names to the older names (adjusted for the right season).

Note, however, that Fitzroy merged with the Brisbane Bears in 1997 to become the Brisbane Lions.
Hence, we cannot use the new team name before 1997, otherwise the Brisbane Lions would have played matches against the Brisbane Lions.
Hence, for now we keep the historically accurate names. However, in subsequent analyses we could choose to neglect seasons before 1997, and could then transform to the new team names.

### Team ordering

Since the match data-files are indexed by team name, this means that each match appears
twice over, i.e. once each in the respective data-files of the opposing teams.
In order to prevent edge duplication in our match graph, we first stipulate a canonical ordering of the teams, i.e. $T_1\prec T_2\prec T_3\cdots$. Then, for each match
with some team A versus some team B, if $A\prec B$ then we designate A as the 'for' team and B as the 'against' team. Conversely, if $A\succ B$, then we designate
A as the 'against' team and B as the 'for' team.

Note that although the canonical team ordering is arbitrary, the resulting 'for' and 'against' designations are deterministic and consistent.

### Edge and vertex attributes

For each match, we know the environmental (i.e. spatio-temporal) information 
that is common for both teams, 
such as the season, the match round within the season, the venue (i.e. the oval), and the date/time of each match.

For each team in the match, we also know if the venue is the team's home ground, and we know the numbers of goals and behinds scored by that team in each quarter. For convenience, we typically label each of the four quarters of a match by an integer suffix.
This information collectively forms the attributes of  the edge between the 'for'  team  and the 'against' team. 
Note that there is no vertex information defined, other than the team name,
since vertex attributes would need to be time-invariant.

### Process the matches

In [6]:
df_edges = match_parser.extract_match_data(matches, use_old_names=True)

In [7]:
print(df_edges.columns)

Index(['season', 'round', 'datetime', 'venue', 'for_team', 'for_is_home',
       'for_goals1', 'for_behinds1', 'for_goals2', 'for_behinds2',
       'for_goals3', 'for_behinds3', 'for_goals4', 'for_behinds4',
       'for_total_score', 'for_match_points', 'for_is_win', 'for_is_draw',
       'for_is_loss', 'against_team', 'against_is_home', 'against_goals1',
       'against_behinds1', 'against_goals2', 'against_behinds2',
       'against_goals3', 'against_behinds3', 'against_goals4',
       'against_behinds4', 'against_total_score', 'against_match_points',
       'against_is_win', 'against_is_draw', 'against_is_loss', 'edge_type'],
      dtype='object')

In [8]:
all_teams = set(df_edges.for_team) | set(df_edges.against_team)
all_teams = sorted(list(all_teams))
print(f"Found {len(all_teams)} teams")
print(all_teams)

Found 22 teams
['Adelaide', 'Brisbane Bears', 'Brisbane Lions', 'Carlton', 'Collingwood', 'Essendon', 'Fitzroy', 'Footscray', 'Fremantle', 'Geelong', 'Gold Coast', 'Greater Western Sydney', 'Hawthorn', 'Kangaroos', 'Melbourne', 'North Melbourne', 'Port Adelaide', 'Richmond', 'St Kilda', 'Sydney', 'West Coast', 'Western Bulldogs']

Observe that the old team names have been retained. We have the 18 modern team names, plus two team renamings, plus two older teams that merged.

In [9]:
df_edges

,season,round,datetime,venue,for_team,for_is_home,for_goals1,for_behinds1,for_goals2,for_behinds2,...,against_goals3,against_behinds3,against_goals4,against_behinds4,against_total_score,against_match_points,against_is_win,against_is_draw,against_is_loss,edge_type
0,2025,R2,Sun 16-Mar-2025 12:05 PM,Adelaide Oval,Adelaide,True,7,2,3,2,...,3,4,3,5,72,0,False,False,True,defeated
1,2025,R3,Sat 22-Mar-2025 1:20 PM,M.C.G.,Adelaide,False,5,5,6,3,...,4,3,6,3,100,0,False,False,True,defeated
2,2025,R4,Sun 30-Mar-2025 2:50 PM,Adelaide Oval,Adelaide,True,4,1,4,4,...,4,0,3,1,78,0,False,False,True,defeated
3,2025,R5,Sat 05-Apr-2025 12:20 PM,Carrara,Adelaide,False,2,4,4,0,...,5,2,3,2,91,4,True,False,False,lost-to
4,2025,R6,Thu 10-Apr-2025 7:10 PM,Adelaide Oval,Adelaide,True,5,3,6,3,...,4,2,5,3,119,4,True,False,False,lost-to
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6867,1990,R13,Sat 30-Jun-1990 2:10 PM,Waverley Park,Footscray,False,1,0,4,4,...,2,6,3,5,73,0,False,False,True,defeated
6868,1990,R14,Sat 07-Jul-1990 2:10 PM,Moorabbin Oval,Footscray,False,3,5,3,0,...,2,4,3,0,78,0,False,False,True,defeated
6869,1990,R15,Sat 14-Jul-1990 2:10 PM,Western Oval,Footscray,True,2,4,5,2,...,4,6,2,4,96,0,False,False,True,defeated
6870,1990,R16,Fri 20-Jul-1990 6:40 PM,W.A.C.A.,Footscray,False,0,4,3,3,...,4,3,5,4,109,4,True,False,False,lost-to
6871,1990,R20,Sat 18-Aug-1990 2:10 PM,Western Oval,Footscray,True,2,5,6,4,...,7,5,5,3,115,4,True,False,False,lost-to

### Order the matches

Note that the matches have potentially been extracted in an arbitrary order.
For convenience, we reorder the matches from the earliest to the latest.
Also note that the date-times are in local format. It is not yet clear whether these have been defined
centrally (e.g. Melbourne/Sydney time), or vary by state.

In [10]:
from datetime import datetime

In [11]:
date_fn = lambda s: datetime.strptime(s, match_parser.DATETIME_FORMAT)

df_edges['_datetime'] = df_edges['datetime'].apply(date_fn)
df_edges.sort_values('_datetime', ascending=True, inplace=True)
df_edges.drop(columns='_datetime', inplace=True)
df_edges.reset_index(drop=True, inplace=True)

In [12]:
df_edges

,season,round,datetime,venue,for_team,for_is_home,for_goals1,for_behinds1,for_goals2,for_behinds2,...,against_goals3,against_behinds3,against_goals4,against_behinds4,against_total_score,against_match_points,against_is_win,against_is_draw,against_is_loss,edge_type
0,1990,R1,Sat 31-Mar-1990 2:10 PM,M.C.G.,Melbourne,False,6,2,4,1,...,4,4,3,4,89,0,False,False,True,defeated
1,1990,R1,Sat 31-Mar-1990 2:10 PM,Waverley Park,Geelong,True,5,3,2,3,...,9,7,10,6,192,4,True,False,False,lost-to
2,1990,R1,Sat 31-Mar-1990 2:10 PM,Princes Park,Carlton,True,6,5,4,4,...,6,3,6,5,104,4,True,False,False,lost-to
3,1990,R1,Sat 31-Mar-1990 2:10 PM,Windy Hill,Essendon,True,7,4,6,7,...,1,3,2,4,60,0,False,False,True,defeated
4,1990,R1,Sat 31-Mar-1990 7:40 PM,Carrara,Brisbane Bears,True,4,3,3,2,...,1,3,3,2,74,0,False,False,True,defeated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6867,2025,SF,Fri 12-Sep-2025 7:10 PM,Adelaide Oval,Adelaide,False,3,2,0,4,...,5,6,3,4,101,4,True,False,False,lost-to
6868,2025,SF,Sat 13-Sep-2025 7:35 PM,Gabba,Brisbane Lions,False,3,5,6,1,...,0,4,1,2,47,0,False,False,True,defeated
6869,2025,PF,Fri 19-Sep-2025 7:40 PM,M.C.G.,Geelong,False,1,3,5,4,...,3,1,4,0,85,0,False,False,True,defeated
6870,2025,PF,Sat 20-Sep-2025 5:15 PM,M.C.G.,Brisbane Lions,False,4,3,0,3,...,2,3,2,1,71,0,False,False,True,defeated
6871,2025,GF,Sat 27-Sep-2025 2:30 PM,M.C.G.,Brisbane Lions,False,1,6,4,0,...,1,2,5,1,75,0,False,False,True,defeated

### Save the graph

In [13]:
df_edges.to_csv(
    os.path.join("..", "data", "matches.csv"),
    index=False
)

---

## Perform Sanity Checking

### Check team names

Since we have decided to use the historically accurate team names, we should check that this aim has
been achieved.

In [14]:
def get_team_seasons(df, team):
    return df.loc[
        (df.for_team == team) | (df.against_team == team),
        'season'
    ]

In [15]:
_seasons = get_team_seasons(df_edges, 'Kangaroos')
assert all((_seasons >= 1999) & (_seasons <= 2007))
_seasons = get_team_seasons(df_edges, 'North Melbourne')
assert all((_seasons < 1999) | (_seasons > 2007))

_seasons = get_team_seasons(df_edges, 'Western Bulldogs')
assert all(_seasons >= 1997)
_seasons = get_team_seasons(df_edges, 'Footscray')
assert all(_seasons < 1997)

_seasons = get_team_seasons(df_edges, 'Brisbane Lions')
assert all(_seasons >= 1997)
_seasons = get_team_seasons(df_edges, 'Fitzroy')
assert all(_seasons < 1997)
_seasons = get_team_seasons(df_edges, 'Brisbane Bears')
assert all(_seasons < 1997)

### Check goals, behinds and points

Each goal is worth 6 points, and each 'behind' is worth 1 point.

In [16]:
for_goals = (
    df_edges.for_goals1 + df_edges.for_goals2 
    + df_edges.for_goals3 + df_edges.for_goals4
)
for_behinds = (
    df_edges.for_behinds1 + df_edges.for_behinds2 
    + df_edges.for_behinds3 + df_edges.for_behinds4
)
for_scores = 6 * for_goals + for_behinds

In [17]:
ind = for_scores == df_edges.for_total_score
assert sum(ind) == len(ind)

In [18]:
against_goals = (
    df_edges.against_goals1 + df_edges.against_goals2 
    + df_edges.against_goals3 + df_edges.against_goals4
)
against_behinds = (
    df_edges.against_behinds1 + df_edges.against_behinds2 
    + df_edges.against_behinds3 + df_edges.against_behinds4
)
against_scores = 6 * against_goals + against_behinds

In [19]:
ind = against_scores == df_edges.against_total_score
assert sum(ind) == len(ind)

### Check matches versus wins, draws and losses

In [20]:
for team in all_teams:
    df = df_edges.loc[df_edges.for_team == team]
    assert len(df) == sum(df.for_is_win) + sum(df.for_is_draw) + sum(df.for_is_loss)
    df = df_edges.loc[df_edges.against_team == team]
    assert len(df) == sum(df.against_is_win) + sum(df.against_is_draw) + sum(df.against_is_loss)

### Check known venues

Occasionally a team changes its home ground to another oval. More frequently, ovals change names due to sponsorship deals. In order to assess any statistics relating to the
match ground, we require a geographical understanding of the names and locations of the various ovals.

In [21]:
df_venues = pd.read_csv(os.path.join("..", "data", "venues.csv"))

In [22]:
df_venues.head()

,venue,from,to,latitude,longitude,ground,suburb_or_town,state,aliases
0,Adelaide Oval,2011,NaN,-34.9156,138.5961,Adelaide Oval,Adelaide,SA,NaN
1,Barossa Oval,2025,NaN,-34.597939,138.885835,Lyndoch Recreation Park,Lyndoch,SA,Barossa Park
2,Bellerive Oval,2012,2019.0,-42.8773,147.3735,Bellerive Oval,Bellerive,TAS,Blundstone Arena
3,Blacktown,2012,2012.0,-33.769444,150.859167,Blacktown International Sportspark Oval,Rooty Hill,NSW,Blacktown ISP Oval;Blacktown ISP
4,Bruce Stadium,1995,1995.0,-35.25,149.102778,Canberra Stadium,Bruce,ACT,GIO Stadium Canberra;GIO Stadium;Bruce Stadium...

In [23]:
df_tmp = pd.merge(df_edges, df_venues, on='venue', how='left')

In [24]:
unknown_venues = set(df.venue[df_tmp.latitude.isna()])
if len(unknown_venues) > 0:
    raise ValueError("Unknown venues: " + ", ".join(unknown_venues))

---

## Training and Testing Data

As discussed in the
[previous](1_introduction.ipynb#Model-validation "Chapter 1: Model validation") chapter,
for the purposes of data analysis and modelling we should partition the data into disjoint *training* and 
*testing* sets. Only the training data should be subject to exploratory data analysis and model building, and the testing data should be utilised only for subsequent model validation. 
During model fitting, model performance should be locally validated against
a *validation* data-set that is disjoint from the training data.
However, rather than statically define such a data-set once only, we leave it up to the machine learning processes, e.g. cross-validation may be performed by dynamic, iterative sampling from the training data.

However, note that, in a 'live' system, the *retrospective* analysis of model building would be coupled with *prospective* prediction of future matches, so these yet-to-be-collected matches would act as ongoing testing data. Monitoring of predictive performance and data distributions over time would then also
allow testing for other issues such as 
[*concept drift*](https://en.wikipedia.org/wiki/Concept_drift "Wikipedia: Concept drift"),
where the model no longer accurately reflects the data (or vice versa), thus indicating a violation of
[temporal invariance](1_introduction.ipynb#Properties-of-invariance "Chapter 1: Properties of invariance").

As an exception to our stated usages of training and testing data,
in the [next](3_feature_extraction.ipynb "Chapter 3: Feature Extraction")
chapter we shall extract historical features for every AFL match,
across  both data-sets. This is permitted to render the summary
match features and outcomes
[independent](1_introduction.ipynb#Causality-and-independence-of-observations "Chapter 1: Causality and independence of observations").
In other words, when a given match is being used for either training or testing purposes, all of the history prior to that match should be available
as generalised, summary features.  

Note that, strictly speaking, we should also partition the resulting data-set of extracted features into training and testing data-sets, in order to
obviate the possibility of contaminating our modelling with testing data.
In practice, we shall permit the loading of all historical data on the assumption that, during the processes of data analysis and model building, only features for matches in the training data-set will be queried and utilised.

### Partition the data

For simplicity, we arbitrarily take all matches from 1990 to 2019 as the training data, and matches from 2020 onwards as testing/validation data. 
A better scheme might have been to randomly partition the matches per season, or even sample the matches completely at random over the whole data-set. However, this would make it harder to test for failures of 
[temporal](1_introduction.ipynb#Failures-of-invariance "Chapter 1: Failures of invariance") representativeness (e.g. concept drift). Hence, we leave entire seasons intact as either training data or testing data.

Note that the year 2020 has also been chosen as the splitting season because it was a very unusual AFL year due to Covid, with heavily modified rules to help avoid contact between players.
Thus, the 2020 season matches were not temporally representative of the usual AFL rules, and should not be modelled like other matches. Hence, we simply leave it out of the training data.

In [25]:
SPLIT_ON_SEASON = 2020

In [26]:
all_seasons = df_edges.season.unique()

In [27]:
split_season = 2020
trn_seasons = all_seasons[all_seasons < SPLIT_ON_SEASON]
tst_seasons = all_seasons[all_seasons >= SPLIT_ON_SEASON]

In [28]:
df_training = df_edges[df_edges.season.isin(trn_seasons)].copy()

In [29]:
df_training.iloc[[0, -1]]

,season,round,datetime,venue,for_team,for_is_home,for_goals1,for_behinds1,for_goals2,for_behinds2,...,against_goals3,against_behinds3,against_goals4,against_behinds4,against_total_score,against_match_points,against_is_win,against_is_draw,against_is_loss,edge_type
0,1990,R1,Sat 31-Mar-1990 2:10 PM,M.C.G.,Melbourne,False,6,2,4,1,...,4,4,3,4,89,0,False,False,True,defeated
5647,2019,GF,Sat 28-Sep-2019 2:30 PM,M.C.G.,Greater Western Sydney,False,1,2,0,4,...,5,4,5,3,114,4,True,False,False,lost-to

In [30]:
df_testing = df_edges[df_edges.season.isin(tst_seasons)].copy()

In [31]:
df_testing.iloc[[0, -1]]

,season,round,datetime,venue,for_team,for_is_home,for_goals1,for_behinds1,for_goals2,for_behinds2,...,against_goals3,against_behinds3,against_goals4,against_behinds4,against_total_score,against_match_points,against_is_win,against_is_draw,against_is_loss,edge_type
5648,2020,R1,Thu 19-Mar-2020 7:40 PM,M.C.G.,Carlton,False,2,1,1,4,...,3,2,2,4,105,4,True,False,False,lost-to
6871,2025,GF,Sat 27-Sep-2025 2:30 PM,M.C.G.,Brisbane Lions,False,1,6,4,0,...,1,2,5,1,75,0,False,False,True,defeated

In [32]:
print("%d training samples" % len(df_training))
print("%d testing samples" % len(df_testing))
p = len(df_training) / len(df_edges)
print("Ratio: %4.2f%% : %4.2f%%" % (100 * p, 100 * (1 - p)))

5648 training samples
1224 testing samples
Ratio: 82.19% : 17.81%

### Save the partitioned data

In [33]:
 df_training.to_csv(
     os.path.join("..", "data", "training_matches.csv"),
     index=False
 )

In [34]:
df_testing.to_csv(
    os.path.join("..", "data", "testing_matches.csv"),
    index=False
)